apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: ghawanni/p4-feed
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: udagram-ghawanni-dev
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: default
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: us-east-1
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: helloworld
        - name: POSTGRESS_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: udagramghawanni
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: udagramghawanni.cf596czfqpcf.us-east-1.rds.amazonaws.com
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: udagramghawanni
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: udagramghawanni      
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret       